/* Mysql table definitions for
   Gerty::SNMP::Postprocess::CISCO_WAN_3G_MIB_dbstore
*/



/* ***********  RSSI per-minute history  ************ */

CREATE TABLE C3G_GSM_RSSI_MINUTE_HISTORY
(
  HOSTNAME              VARCHAR(150) NOT NULL,
  PHY_IDX               INTEGER(6) NOT NULL,
  MEASURE_TS            DATETIME NOT NULL,
  WEAKEST_RSSI          FLOAT NOT NULL,
  CONSTRAINT UC01 UNIQUE (HOSTNAME, PHY_IDX, MEASURE_TS)
);

CREATE INDEX C3G_GSM_RSSI_MINUTE_HISTORY_I01
  ON C3G_GSM_RSSI_MINUTE_HISTORY(HOSTNAME, PHY_IDX, MEASURE_TS);

CREATE INDEX C3G_GSM_RSSI_MINUTE_HISTORY_I02
  ON C3G_GSM_RSSI_MINUTE_HISTORY(MEASURE_TS);

CREATE INDEX C3G_GSM_RSSI_MINUTE_HISTORY_I03
  ON C3G_GSM_RSSI_MINUTE_HISTORY(HOSTNAME, MEASURE_TS);


/* ***********  Service type  ************ */

CREATE TABLE C3G_GSM_SRVTYPE
(
  HOSTNAME              VARCHAR(150) NOT NULL,
  PHY_IDX               INTEGER(6) NOT NULL,
  MEASURE_TS            DATETIME NOT NULL,
  GSM_SRV_TYPE          VARCHAR(12) NOT NULL,
  GSM_BAND              VARCHAR(12) NOT NULL,
  CONSTRAINT UC02 UNIQUE (HOSTNAME, PHY_IDX, MEASURE_TS)  
);

CREATE INDEX C3G_GSM_SRVTYPE_I01
  ON C3G_GSM_SRVTYPE(HOSTNAME, PHY_IDX, MEASURE_TS);

CREATE INDEX C3G_GSM_SRVTYPE_I02
  ON C3G_GSM_SRVTYPE(MEASURE_TS);

CREATE INDEX C3G_GSM_SRVTYPE_I03
  ON C3G_GSM_SRVTYPE(GSM_SRV_TYPE, MEASURE_TS);

CREATE INDEX C3G_GSM_SRVTYPE_I04
  ON C3G_GSM_SRVTYPE(GSM_BAND, MEASURE_TS);



/* *********** Hardware inventory  ************ */

CREATE TABLE C3G_HARDWAREINFO
(
  HOSTNAME              VARCHAR(150) NOT NULL,
  PHY_IDX               INTEGER(6) NOT NULL,
  BEGIN_TS              DATETIME NOT NULL,
  END_TS                DATETIME NOT NULL,
  MD5HASH               VARCHAR(32) NOT NULL,
  HW_JSON               BLOB NOT NULL,
  CONSTRAINT UC03 UNIQUE (HOSTNAME, PHY_IDX, BEGIN_TS)  
);

CREATE INDEX C3G_HARDWAREINFO_I01
  ON C3G_HARDWAREINFO(HOSTNAME, PHY_IDX, BEGIN_TS);

CREATE INDEX C3G_HARDWAREINFO_I02
  ON C3G_HARDWAREINFO(HOSTNAME, BEGIN_TS);