// Oracle table definitions for
//   Gerty::Netconf::Postprocess::JunOSDBStore
//


// *********  Current MAC counts for ********

CREATE TABLE JNX_VPLS_CURRENT_MAC_COUNT
(
  HOSTNAME              VARCHAR2(150) NOT NULL,
  INSTANCE_NAME         VARCHAR2(150) NOT NULL,
  INTERFACE_NAME        VARCHAR2(60) DEFAULT NULL,
  VLAN_NUM              NUMBER(11) DEFAULT NULL,
  MAC_COUNT             NUMBER(11) NOT NULL,
  LAST_UPDATED          DATE NOT NULL,
  CONSTRAINT JNX_VPLS_CURRENT_MAC_COUNT_C01
    UNIQUE(HOSTNAME, INSTANCE_NAME, INTERFACE_NAME, VLAN_NUM)
);


CREATE INDEX JNX_VPLS_CURRENT_MAC_COUNT_I01
  ON JNX_VPLS_CURRENT_MAC_COUNT(INSTANCE_NAME);

CREATE INDEX JNX_VPLS_CURRENT_MAC_COUNT_I02
  ON JNX_VPLS_CURRENT_MAC_COUNT(VLAN_NUM);



// ***********  MAC count history  ************

CREATE TABLE JNX_VPLS_HISTORY_MAC_COUNT
(
  HOSTNAME              VARCHAR2(150) NOT NULL,
  INSTANCE_NAME         VARCHAR2(150) NOT NULL,
  INTERFACE_NAME        VARCHAR2(60) DEFAULT NULL,
  VLAN_NUM              NUMBER(11) DEFAULT NULL,
  MAC_COUNT             NUMBER(11) NOT NULL,
  UPDATE_TS             DATE NOT NULL
);

CREATE INDEX JNX_VPLS_HISTORY_MAC_COUNT_I01
  ON JNX_VPLS_HISTORY_MAC_COUNT(HOSTNAME, INSTANCE_NAME, INTERFACE_NAME);

CREATE INDEX JNX_VPLS_HISTORY_MAC_COUNT_I02
  ON JNX_VPLS_HISTORY_MAC_COUNT(INSTANCE_NAME);

CREATE INDEX JNX_VPLS_HISTORY_MAC_COUNT_I03
  ON JNX_VPLS_HISTORY_MAC_COUNT(VLAN_NUM);

CREATE INDEX JNX_VPLS_HISTORY_MAC_COUNT_I04
  ON JNX_VPLS_HISTORY_MAC_COUNT(UPDATE_TS);
