// Oracle table definitions for
//   Gerty::Netconf::Postprocess::JunOSDBStore
//
// TS_ADDED is a Unix timestamp for each record. Records grow with time, and
// it's up to some external process to clean them up */


// *********  Total MAC counts for each routing instance ********

CREATE TABLE JNX_VPLS_TOTAL_MAC_COUNT
(
  HOSTNAME              VARCHAR2(150) NOT NULL,
  INSTANCE_NAME         VARCHAR2(150) NOT NULL,
  MAC_COUNT             NUMBER(11) NOT NULL,
  TS_ADDED              NUMBER(11) NOT NULL
);


CREATE INDEX JNX_VPLS_TOTAL_MAC_COUNT_01
  ON JNX_VPLS_TOTAL_MAC_COUNT(HOSTNAME, INSTANCE_NAME);

CREATE INDEX JNX_VPLS_TOTAL_MAC_COUNT_02
  ON JNX_VPLS_TOTAL_MAC_COUNT(TS_ADDED);

CREATE INDEX JNX_VPLS_TOTAL_MAC_COUNT_03
  ON JNX_VPLS_TOTAL_MAC_COUNT(INSTANCE_NAME);



// *********  MAC counts for each interface in a routing instance ********

CREATE TABLE JNX_VPLS_INTF_MAC_COUNT
(
  HOSTNAME              VARCHAR2(150) NOT NULL,
  INSTANCE_NAME         VARCHAR2(150) NOT NULL,
  INTERFACE_NAME        VARCHAR2(60) NOT NULL,
  MAC_COUNT             NUMBER(11) NOT NULL,
  TS_ADDED              NUMBER(11) NOT NULL
);

CREATE INDEX JNX_VPLS_INTF_MAC_COUNT_01
  ON JNX_VPLS_INTF_MAC_COUNT(HOSTNAME, INSTANCE_NAME, INTERFACE_NAME);

CREATE INDEX JNX_VPLS_INTF_MAC_COUNT_02
  ON JNX_VPLS_INTF_MAC_COUNT(TS_ADDED);

CREATE INDEX JNX_VPLS_INTF_MAC_COUNT_03
  ON JNX_VPLS_INTF_MAC_COUNT(INSTANCE_NAME);


// *********  MAC counts for each VLAN in a routing instance ********

CREATE TABLE JNX_VPLS_VLAN_MAC_COUNT
(
  HOSTNAME              VARCHAR2(150) NOT NULL,
  INSTANCE_NAME         VARCHAR2(150) NOT NULL,
  VLAN_NUM              NUMBER(11) NOT NULL,
  MAC_COUNT             NUMBER(11) NOT NULL,
  TS_ADDED              NUMBER(11) NOT NULL
);

CREATE INDEX JNX_VPLS_VLAN_MAC_COUNT_01
  ON JNX_VPLS_VLAN_MAC_COUNT(HOSTNAME, INSTANCE_NAME, VLAN_NUM);

CREATE INDEX JNX_VPLS_VLAN_MAC_COUNT_02
  ON JNX_VPLS_VLAN_MAC_COUNT(TS_ADDED);

CREATE INDEX JNX_VPLS_VLAN_MAC_COUNT_03
  ON JNX_VPLS_VLAN_MAC_COUNT(INSTANCE_NAME);

CREATE INDEX JNX_VPLS_VLAN_MAC_COUNT_04
  ON JNX_VPLS_VLAN_MAC_COUNT(VLAN_NUM);


